const translations = {
  uk: {
    logo: "Марафон Трансформації",
    hedernavtext1: "Основна частина",
    hedernavtext2: "Раціон",
    hedernavtext3: "Розрахунок норми КБЖВ",
    // aboutMaraphonTitle1: "«9 днів, які можуть змінити твоє життя»",
    // aboutMaraphonText1:
    //   "Ідеальне поєднання системного підходу в трьох сферах:\n✅ Гроші та блокуючі установки\n✅ Тіло як відображення душі\n✅ Продажі через Instagram",
    aboutMaraphonButton: "Розрахунок норми КБЖВ",
    aboutMaraphonTitleMain: "🔥 Марафон змін: тіло, яке слухається тебе",
    aboutMaraphonSubtitle: "14 днів — щоб побачити реальні зміни.",
    aboutMaraphonDescription1: "Ти отримаєш не мотиваційні гасла, а систему, яка працює: чітке меню, збалансований раціон, практичні поради й підтримку, щоб тіло почало слухатися тебе з першого тижня.",
    aboutMaraphonDescription2: "Ніяких дієт, виснаження чи “зривів”. Ти навчишся їсти правильно, мати енергію й бачити, як вага реагує на твою послідовність, а не на випадковість.",
    aboutMaraphonPoint1: " мінус 2–4 кг за 14 днів без стресу",
    aboutMaraphonPoint2: " відновлення режиму сну та харчування",
    aboutMaraphonPoint3: " нова легкість у тілі й голові",
    aboutMaraphonPoint4: " сила волі без надриву",
    aboutMaraphonConclusion1: "Це не марафон заради цифр — це старт нової дисципліни, у якій турбота про себе стає формою вдячності за життя.",
    aboutMaraphonConclusion2: "Твоє тіло вміє слухатися. Йому просто потрібно, щоб ти нарешті заговорив із ним однією мовою.",
    dayText: "Як приготувати? Склад. КБЖВ.",
    dayButton: "До меню",
    aboutMaraphonButton2: "повернутися на головну сторінку",
    forWhomTitle: "Для кого марафон",
    forWhom1: "Прагнеш привести тіло в порядок, поліпшити фігуру і харчування.",
    forWhom2: "Хочеш взяти відповідальність за життя і перестати відкладати.",
    forWhom3:
      "Хочеш заробляти і реалізовуватися через Instagram та інші можливості.",
    forWhom4: "Готовий розвиватися системно і змінювати звички на практиці.",
    forWhomText:
      "Відчуваєш, що можеш більше — заробляти більше, бути енергійнішим, сильнішим, продуктивнішим.",

    aboutAuthorsTitle: "Про автора",
    aboutAuthorsText:
      "Сергій Чертилин — ведучий марафону, місіонер і автор багатьох проектів з особистої трансформації та самореалізації. Пройшов шлях від 140 кг до мінус 55 кг, повністю змінивши тіло, звички та підхід до життя. Знає, як будувати дисципліну, керувати собою та досягати цілей на практиці.",

    programTitle: "Програма",
    program1: "9 днів спільної роботи",
    program2: "3 головні теми для вдосконалення та особистого зростання",
    program3: "4 зустрічі в прямих ефірах",
    program4: "6 ефективних завдань",

    day1Title: "День перший",
    day1Breakfast: "🍽 Сніданок",
    composition: "Склад:",
    howToCook: "Як приготувати:",
    nutrition: "КБЖВ (на порцію):",

    day1Breakfast1: "Овсяна крупа – 50 г",
    day1Breakfast2: "Молоко 3,2% – 50 мл",
    day1Breakfast3: "Вода – 100 мл",
    day1Breakfast4: "Сливочне масло – 6 г",
    day1Breakfast5: "Курага – 15 г",
    day1Breakfast6: "Чорнослив – 15 г",
    day1Breakfast7: "Ізюм – 15 г",
    day1Breakfast8: "Куряче яйце – 1 шт.",
    day1Breakfast9: "Банан – 120 г",
    day1Breakfast10: "Грецький йогурт без добавок – 140 г",

    day1BreakfastStep1: "Зваріть кашу на воді та молоці.",
    day1BreakfastStep2: "Додайте масло та сухофрукти.",
    day1BreakfastStep3: "Яйце відваріть або обсмажте без олії.",
    day1BreakfastStep4: "Подайте кашу з яйцем, а як десерт – банан з йогуртом.",

    day1BreakfastNutrition1: "🔥 Калорії: ~656 ккал",
    day1BreakfastNutrition2: "🥩 Білки: ~31,4 г",
    day1BreakfastNutrition3: "🥑 Жири: ~16,4 г",
    day1BreakfastNutrition4: "🍞 Вуглеводи: ~93 г",

    day1Lunch: "🍲 Обід",
    day1Lunch1: "Курячий бульйон – 250 мл (можна без нього)",
    day1Lunch2: "Яєчна локшина – 45 г",
    day1Lunch3: "Куряче філе – 140 г",
    day1Lunch4: "Помідори – 100 г",
    day1Lunch5: "Огірки – 100 г",
    day1Lunch6: "Салат айсберг – 30 г",
    day1Lunch7: "Оливкова олія – 7 мл",
    day1Lunch8: "Ряжанка 1% – 120 мл",
    day1Lunch9: "Грецькі горіхи – 30 г (~5 шт.)",

    day1LunchStep1: "Зваріть легкий суп із бульйону та локшини.",
    day1LunchStep2: "Запечіть куряче філе зі спеціями.",
    day1LunchStep3: "Зробіть овочевий салат і заправте олією.",
    day1LunchStep4: "Додаток — ряжанка з горіхами.",

    day1LunchNutrition1: "🔥 Калорії: ~786 ккал",
    day1LunchNutrition2: "🥩 Білки: ~64,2 г",
    day1LunchNutrition3: "🥑 Жири: ~35,3 г",
    day1LunchNutrition4: "🍞 Вуглеводи: ~49,2 г",

    day1Dinner: "🍳 Вечеря",
    day1Dinner1: "Яйце – 2 шт.",
    day1Dinner2: "Яєчний білок – 2 шт.",
    day1Dinner3: "Шпинат – 30 г",
    day1Dinner4: "Шампіньйони – 50 г",
    day1Dinner5: "Сливочне масло – 5 г",
    day1Dinner6: "Помідори – 100 г",
    day1Dinner7: "Огірки – 100 г",
    day1Dinner8: "Салат айсберг – 30 г",
    day1Dinner9: "Оливкова олія – 3 мл",
    day1Dinner10: "Лимонний сік – 3 мл",
    day1Dinner11: "Морська капуста – 60 г",
    day1Dinner12: "Креветки – 80 г",
    day1Dinner13: "Морква (соломкою) – 50 г",
    day1Dinner14: "Кукурудза – 20 г",

    day1DinnerStep1:
      "Приготуйте яєчню з яйць і білків зі шпинатом і шампіньйонами на маслі.",
    day1DinnerStep2:
      "Зробіть овочевий салат і заправте олією та лимонним соком.",
    day1DinnerStep3:
      "Відваріть креветки й змішайте їх з морською капустою, морквою та кукурудзою.",

    day1DinnerNutrition1: "🔥 Калорії: ~459 ккал",
    day1DinnerNutrition2: "🥩 Білки: ~44,1 г",
    day1DinnerNutrition3: "🥑 Жири: ~21,3 г",
    day1DinnerNutrition4: "🍞 Вуглеводи: ~24 г",
    day2Title: "День другий",
    day2Breakfast: "🍽 Сніданок",
    composition: "Склад:",
    howToCook: "Як приготувати:",
    nutrition: "КБЖВ (на порцію):",

    day2Breakfast1: "Гречка (суха) – 70 г",
    day2Breakfast2: "Сливочне масло – 8 г",
    day2Breakfast3: "Твердий сир – 30 г",
    day2Breakfast4: "Хліб бородинський – 20 г (~1 шматок)",
    day2Breakfast5: "Рисові хлібці – 20 г (~2 шт.)",
    day2Breakfast6: "Арахісова паста – 14 г",
    day2Breakfast7: "Банан – 45 г",
    day2Breakfast8: "Кава – 200 мл",
    day2Breakfast9: "Гіркий шоколад – 5 г",

    day2BreakfastStep1:
      "Залити гречку окропом і настоювати або зварити, перед подачею додати масло.",
    day2BreakfastStep2: "Зробити бутерброд: хліб + сир.",
    day2BreakfastStep3:
      "Приготувати рисові хлібці з арахісовою пастою і бананом.",
    day2BreakfastStep4: "Подати з кавою і шматочком шоколаду.",

    day2BreakfastNutrition1: "🔥 Калорії: ~716 ккал",
    day2BreakfastNutrition2: "🥩 Білки: ~28,5 г",
    day2BreakfastNutrition3: "🥑 Жири: ~30,6 г",
    day2BreakfastNutrition4: "🍞 Вуглеводи: ~83,2 г",

    day2Lunch: "🍲 Обід",
    day2Lunch1: "Картопля – 180 г",
    day2Lunch2: "Куряча печінка – 140 г",
    day2Lunch3: "Цибуля – 50 г",
    day2Lunch4: "Сметана 10% – 30 г",
    day2Lunch5: "Олія соняшникова – 7 мл",
    day2Lunch6: "Хліб бородинський – 30 г (~1 шматок)",
    day2Lunch7: "Авокадо – 40 г",
    day2Lunch8: "Слабосолона сьомга – 30 г",

    day2LunchStep1: "Відварити або запекти картоплю.",
    day2LunchStep2:
      "Печінку обсмажити з цибулею, потім протушкувати у суміші сметани, води та спецій.",
    day2LunchStep3:
      "Приготувати тост: хліб + розім’яте авокадо + шматочки сьомги.",

    day2LunchNutrition1: "🔥 Калорії: ~680 ккал",
    day2LunchNutrition2: "🥩 Білки: ~41,9 г",
    day2LunchNutrition3: "🥑 Жири: ~29,7 г",
    day2LunchNutrition4: "🍞 Вуглеводи: ~65,8 г",

    day2Dinner: "🍳 Вечеря",
    day2Dinner1: "Яйця – 2 шт.",
    day2Dinner2: "Молоко 2,5% – 150 мл",
    day2Dinner3: "Сир – 40 г",
    day2Dinner4: "Помідор – 50 г",
    day2Dinner5: "Кефір 1% – 250 мл",
    day2Dinner6: "Трохи кориці (за бажанням)",

    day2DinnerStep1: "Змішати яйця, молоко, сир і нарізаний помідор.",
    day2DinnerStep2:
      "Збити суміш і готувати 2–2,5 хв у мікрохвильовці або на сковороді/у духовці.",
    day2DinnerStep3:
      "Подати білковий омлет, а до вечері випити кефір з корицею.",

    day2DinnerNutrition1: "🔥 Калорії: ~406 ккал",
    day2DinnerNutrition2: "🥩 Білки: ~30,6 г",
    day2DinnerNutrition3: "🥑 Жири: ~17,4 г",
    day2DinnerNutrition4: "🍞 Вуглеводи: ~22,8 г",

    day2Summary: "📊 Підсумок за день (День 2)",
    day2SummaryCalories: "🔥 Калорії: ~1802 ккал",
    day2SummaryProteins: "🥩 Білки: ~101 г",
    day2SummaryFats: "🥑 Жири: ~87,7 г",
    day2SummaryCarbs: "🍞 Вуглеводи: ~151,8 г",

    day3Title: "День третій",
    day3Breakfast: "🍽 Сніданок",
    day3Lunch: "🍲 Обід",
    day3Dinner: "🐟 Вечеря",
    composition: "Склад:",
    howToCook: "Як приготувати:",
    nutrition: "КБЖВ:",

    day3Breakfast1: "Вівсяні пластівці – 50 г",
    day3Breakfast2: "Молоко – 40 мл",
    day3Breakfast3: "Яйце – 1 шт.",
    day3Breakfast4: "Какао – 10 г",
    day3Breakfast5: "Ківі – 60 г",
    day3Breakfast6: "Кокосова паста – 12 г",
    day3Breakfast7: "Апельсин – 80 г",
    day3Breakfast8: "Груша – 80 г",
    day3Breakfast9: "Яблуко – 80 г",
    day3Breakfast10: "Сметана 10% – 30 г",
    day3Breakfast11: "Кедрові горіхи – 15 г",
    day3BreakfastStep1:
      "Збити молоко з яйцем до однорідності, додати пластівці та какао, залишити на 7 хвилин для набухання.",
    day3BreakfastStep2:
      "Обсмажити з двох сторін вівсяний млинець, змастити пастою і покласти ківі, скрутити.",
    day3BreakfastStep3:
      "Нарізати фрукти, змішати зі сметаною та посипати кедровими горіхами.",
    day3BreakfastNutrition1: "🔥 Калорії: ~498 ккал",
    day3BreakfastNutrition2: "🥩 Білки: ~17,2 г",
    day3BreakfastNutrition3: "🥑 Жири: ~18,6 г",
    day3BreakfastNutrition4: "🍞 Вуглеводи: ~63,7 г",

    day3Lunch1: "М’ясний бульйон – 220 мл (за бажанням можна прибрати)",
    day3Lunch2: "Квашена капуста – 100 г",
    day3Lunch3: "Цільнозернові макарони – 50 г",
    day3Lunch4: "Свининий фарш – 90 г",
    day3Lunch5: "Цибуля – 40 г",
    day3Lunch6: "Томатна паста – 30 г",
    day3Lunch7: "Фундук – 20 г (~20 шт.)",
    day3Lunch8: "Сушений інжир – 3 шт. (~30 г)",
    day3LunchStep1: "Приготувати щі на м’ясному бульйоні.",
    day3LunchStep2:
      "Для другої страви обсмажити фарш з цибулею, додати томатну пасту і воду, тушкувати.",
    day3LunchStep3: "Відварити макарони та змішати з фаршем.",
    day3LunchNutrition1: "🔥 Калорії: ~790 ккал",
    day3LunchNutrition2: "🥩 Білки: ~32,8 г",
    day3LunchNutrition3: "🥑 Жири: ~37,1 г",
    day3LunchNutrition4: "🍞 Вуглеводи: ~73,9 г",

    day3Dinner1: "Філе хека – 150 г",
    day3Dinner2: "Броколі – 70 г",
    day3Dinner3: "Цвітна капуста – 100 г",
    day3Dinner4: "Вершки 20% – 30 мл",
    day3Dinner5: "Оливки – 20 г",
    day3Dinner6: "Квашена капуста – 50 г",
    day3Dinner7: "Оливкова олія – 5 мл",
    day3Dinner8: "М’який знежирений сир – 170 г",
    day3Dinner9: "Огірок – 40 г",
    day3Dinner10: "Кріп – 10 г",
    day3Dinner11: "Зелена цибуля – 10 г",
    day3DinnerStep1:
      "Запекти рибу з броколі та цвітною капустою у вершках з водою.",
    day3DinnerStep2:
      "Викласти на тарілку з оливками та квашеною капустою, заправленою олією.",
    day3DinnerStep3: "Нарізати огірок та зелень, змішати з сиром.",
    day3DinnerNutrition1: "🔥 Калорії: ~513 ккал",
    day3DinnerNutrition2: "🥩 Білки: ~53,2 г",
    day3DinnerNutrition3: "🥑 Жири: ~27,3 г",
    day3DinnerNutrition4: "🍞 Вуглеводи: ~27,0 г",
    day4Title: "День четвертий",
    day4Breakfast: "🍽 Сніданок",
    composition: "Склад:",
    howToCook: "Як приготувати:",
    nutrition: "КБЖВ:",

    day4Breakfast1: "Молоко 3,2% – 160 мл",
    day4Breakfast2: "Банан – 80 г",
    day4Breakfast3: "Творог 5% – 100 г",
    day4Breakfast4: "Квітковий мед – 15 г",
    day4Breakfast5: "Зелене яблуко – 120 г",

    day4BreakfastStep1: "Нарізати банан.",
    day4BreakfastStep2:
      "Збити банан, молоко, творог і мед у блендері до однорідності.",
    day4BreakfastStep3: "Нарізати яблуко окремо, подати до смузі.",

    day4BreakfastNutrition1: "🔥 Калорії: ~465 ккал",
    day4BreakfastNutrition2: "🥩 Білки: ~28 г",
    day4BreakfastNutrition3: "🥑 Жири: ~12 г",
    day4BreakfastNutrition4: "🍞 Вуглеводи: ~68 г",

    day4Lunch: "🍲 Обід",
    day4Lunch1: "Кабачки – 80 г",
    day4Lunch2: "Цвітна капуста – 80 г",
    day4Lunch3: "Цибуля – 50 г",
    day4Lunch4: "Шпинат – 40 г",
    day4Lunch5: "Вершки 20% – 30 мл",
    day4Lunch6: "Гречка суха – 60 г",
    day4Lunch7: "Шампіньйони – 120 г",
    day4Lunch8: "Морква – 30 г",
    day4Lunch9: "Сливочне масло – 7 г",
    day4Lunch10: "Олія соняшникова – 4 г",
    day4Lunch11: "Слайси пшеничні – 20 г",
    day4Lunch12: "Урбеч з насіння льону – 10 г",
    day4Lunch13: "Сир адигейський – 30 г",

    day4LunchStep1:
      "Зробити крем-суп з кабачків, цвітної капусти, цибулі та шпинату з вершками.",
    day4LunchStep2:
      "Зварити гречку, обсмажити гриби з морквою на маслі, змішати з гречкою.",
    day4LunchStep3: "Зробити бутерброди: намазати урбеч на хліб, додати сир.",

    day4LunchNutrition1: "🔥 Калорії: ~600 ккал",
    day4LunchNutrition2: "🥩 Білки: ~34 г",
    day4LunchNutrition3: "🥑 Жири: ~23 г",
    day4LunchNutrition4: "🍞 Вуглеводи: ~70 г",

    day4Dinner: "🐟 Вечеря",
    day4Dinner1: "Філе індички – 120 г",
    day4Dinner2: "Болгарський перець – 150 г",
    day4Dinner3: "Цибуля – 50 г",
    day4Dinner4: "Сметана 15% – 20 г",
    day4Dinner5: "Томатна паста – 20 г",
    day4Dinner6: "Огірки – 100 г",
    day4Dinner7: "Помідори – 100 г",
    day4Dinner8: "Зелена редька – 50 г",
    day4Dinner9: "Фасоля стручкова – 80 г",
    day4Dinner10: "Салат – 15 г",
    day4Dinner11: "Оливкова олія – 7 мл",
    day4Dinner12: "Сік лимона – 3 мл",
    day4Dinner13: "Білки яєць – 4 шт.",

    day4DinnerStep1:
      "Тушкувати індичку з перцем, цибулею, томатною пастою і сметаною до готовності.",
    day4DinnerStep2: "Зварити фасолю та яйця, нарізати.",
    day4DinnerStep3:
      "Зробити салат: змішати фасолю, яйця, огірки, помідори, редьку і салат, заправити олією та соком лимона.",
    day4DinnerStep4: "Подати м’ясо з тушеними овочами та салатом.",

    day4DinnerNutrition1: "🔥 Калорії: ~727 ккал",
    day4DinnerNutrition2: "🥩 Білки: ~61 г",
    day4DinnerNutrition3: "🥑 Жири: ~26,1 г",
    day4DinnerNutrition4: "🍞 Вуглеводи: ~48,4 г",
    day5Title: "День п’ятий",
    day5Breakfast: "🍽 Сніданок",
    day5Lunch: "🍲 Обід",
    day5Dinner: "🐟 Вечеря",
    composition: "Склад:",
    howToCook: "Як приготувати:",
    nutrition: "КБЖВ:",

    // Сніданок
    day5Breakfast1: "Пшоно – 70 г",
    day5Breakfast2: "Молоко 3,2% – 120 мл",
    day5Breakfast3: "Вода – 160 мл",
    day5Breakfast4: "Груша – 60 г",
    day5Breakfast5: "Кедрові горіхи – 5 г",
    day5Breakfast6: "Вершкове масло – 5 г",
    day5Breakfast7: "Зелене яблуко – 140 г",
    day5Breakfast8: "Твердий сир – 35 г",
    day5BreakfastStep1:
      "Зварити пшоно на суміші води та молока до готовності, додати вершкове масло.",
    day5BreakfastStep2:
      "Нарізати грушу та викласти зверху каші, посипати кедровими горіхами.",
    day5BreakfastStep3: "Яблуко нарізати та подати разом із твердим сиром.",
    day5BreakfastNutrition1: "🔥 Калорії: ~540 ккал",
    day5BreakfastNutrition2: "🥩 Білки: ~22 г",
    day5BreakfastNutrition3: "🥑 Жири: ~16 г",
    day5BreakfastNutrition4: "🍞 Вуглеводи: ~72 г",

    // Обід
    day5Lunch1: "Курячий бульйон – 220 мл (можна прибрати за бажанням)",
    day5Lunch2: "Овочева суміш (заморожена) – 120 г",
    day5Lunch3: "Рис жасминовий – 30 г",
    day5Lunch4: "Курячий фарш – 115 г",
    day5Lunch5: "Цибуля – 20 г",
    day5Lunch6: "Морква – 20 г",
    day5Lunch7: "Яйце – 1 шт.",
    day5Lunch8: "Творог 1% – 110 г",
    day5Lunch9: "Вівсяне молоко – 110 мл",
    day5Lunch10: "Банан – 80 г",
    day5LunchStep1:
      "На курячому бульйоні приготувати овочевий суп із заморожених овочів.",
    day5LunchStep2:
      "Відварити рис. Зробити котлети: змішати фарш із цибулею, морквою та яйцем, приправити сіллю й перцем, обсмажити або запекти.",
    day5LunchStep3:
      "Для білково-вуглеводного напою: змішати творог, вівсяне молоко та банан у блендері до однорідності.",
    day5LunchNutrition1: "🔥 Калорії: ~700 ккал",
    day5LunchNutrition2: "🥩 Білки: ~55 г",
    day5LunchNutrition3: "🥑 Жири: ~20 г",
    day5LunchNutrition4: "🍞 Вуглеводи: ~80 г",

    // Вечеря
    day5Dinner1: "Консервований тунець – 150 г",
    day5Dinner2: "Помідор – 100 г",
    day5Dinner3: "Сир пармезан – 30 г",
    day5Dinner4: "Базилік – 15 г",
    day5Dinner5: "Червона цибуля – 30 г",
    day5Dinner6: "Солодкий перець – 80 г",
    day5Dinner7: "Оливкова олія – 7 мл",
    day5Dinner8: "Клубніка – 100 г",
    day5Dinner9: "Грецький йогурт 2% – 140 г",
    day5DinnerStep1:
      "Нарізати солодкий перець, помідор, цибулю та викласти на тарілку з базиліком.",
    day5DinnerStep2:
      "Додати тунець, посипати тертим пармезаном, заправити оливковою олією.",
    day5DinnerStep3:
      "Клубніку змішати з йогуртом як десерт або додаток до салату.",
    day5DinnerNutrition1: "🔥 Калорії: ~569 ккал",
    day5DinnerNutrition2: "🥩 Білки: ~59 г",
    day5DinnerNutrition3: "🥑 Жири: ~28 г",
    day5DinnerNutrition4: "🍞 Вуглеводи: ~64,1 г",

    // Підсумок
    day5totalNutrition: "Загальний КБЖВ:",
    day5totalNutrition1: "🔥 Калорії: ~1809 ккал",
    day5totalNutrition2: "🥩 Білки: ~136 г",
    day5totalNutrition3: "🥑 Жири: ~64 г",
    day5totalNutrition4: "🍞 Вуглеводи: ~165,1 г",
    day6Title: "День шостий",

    day6Breakfast: "🍽 Сніданок",
    composition: "Склад",
    day6Breakfast1: "Вівсяні пластівці (довга варка) – 30 г",
    day6Breakfast2: "Молоко 3,2% – 200 мл",
    day6Breakfast3: "Ряжанка 1% – 100 мл",
    day6Breakfast4: "Насіння соняшника – 10 г",
    day6Breakfast5: "Полуниця – 100 г",
    day6Breakfast6: "Мед квітковий – 15 г",
    howToCook: "Як приготувати",
    day6BreakfastStep1:
      "Хлопья залити молоком і ряженкою, довести до готовності",
    day6BreakfastStep2: "Додати нарізану полуницю, посипати насінням",
    day6BreakfastStep3: "Полити медом і подавати",
    nutrition: "КБЖВ",
    day6BreakfastNutrition1: "🔥 Калорії: ~540 ккал",
    day6BreakfastNutrition2: "🥩 Білки: ~22 г",
    day6BreakfastNutrition3: "🥑 Жири: ~16 г",
    day6BreakfastNutrition4: "🍞 Вуглеводи: ~72 г",

    day6Lunch: "🍲 Обід",
    day6Lunch1: "Курячий бульйон – 220 мл",
    day6Lunch2: "Суміш овочів (заморожена) – 120 г",
    day6Lunch3: "Рис жасмин – 30 г",
    day6Lunch4: "Курячий фарш – 115 г",
    day6Lunch5: "Цибуля – 20 г",
    day6Lunch6: "Морква – 20 г",
    day6Lunch7: "Яйце – 1 шт",
    day6Lunch8: "Творог 1% – 110 г",
    day6Lunch9: "Вівсяне молоко – 110 мл",
    day6Lunch10: "Банан – 80 г",
    day6LunchStep1: "На бульйоні приготувати овочевий суп",
    day6LunchStep2:
      "Відварити рис. Зробити котлети: змішати фарш з цибулею, морквою та яйцем, приправити сіллю та перцем, обсмажити або запекти",
    day6LunchStep3:
      "Білково-вуглеводний напій: змішати творог, вівсяне молоко та банан у блендері",
    day6LunchNutrition1: "🔥 Калорії: ~700 ккал",
    day6LunchNutrition2: "🥩 Білки: ~55 г",
    day6LunchNutrition3: "🥑 Жири: ~20 г",
    day6LunchNutrition4: "🍞 Вуглеводи: ~80 г",

    day6Dinner: "🐟 Вечеря",
    day6Dinner1: "Консервований тунець – 150 г",
    day6Dinner2: "Помідор – 100 г",
    day6Dinner3: "Сир пармезан – 30 г",
    day6Dinner4: "Базилік – 15 г",
    day6Dinner5: "Червона цибуля – 30 г",
    day6Dinner6: "Солодкий перець – 80 г",
    day6Dinner7: "Оливкова олія – 7 мл",
    day6Dinner8: "Полуниця – 100 г",
    day6Dinner9: "Грецький йогурт 2% – 140 г",
    day6DinnerStep1:
      "Нарізати перець, помідор, цибулю, викласти на тарілку з базиліком",
    day6DinnerStep2:
      "Додати тунець, посипати тертим пармезаном, заправити оливковою олією",
    day6DinnerStep3:
      "Полуницю змішати з йогуртом як десерт або доповнення до салату",
    day6DinnerNutrition1: "🔥 Калорії: ~569 ккал",
    day6DinnerNutrition2: "🥩 Білки: ~59 г",
    day6DinnerNutrition3: "🥑 Жири: ~28 г",
    day6DinnerNutrition4: "🍞 Вуглеводи: ~64,1 г",

    day5totalNutrition: "Загальний КБЖВ",
    day6TotalNutrition1: "🔥 Калорії: ~1809 ккал",
    day6TotalNutrition2: "🥩 Білки: ~136 г",
    day6TotalNutrition3: "🥑 Жири: ~64 г",
    day6TotalNutrition4: "🍞 Вуглеводи: ~165,1 г",
    day7Title: "День сьомий",
    day7Breakfast: "🍽 Сніданок",
    composition: "Склад",
    howToCook: "Як приготувати",
    nutrition: "КБЖВ",
    day7Breakfast1: "Яйця – 3 шт.",
    day7Breakfast2: "Сметана 15% – 30 г",
    day7Breakfast3: "Кріп – 15 г",
    day7Breakfast4: "Помідори – 80 г",
    day7Breakfast5: "Творожний сир – 10 г",
    day7Breakfast6: "Хліб зерновий – 30 г (~1 скибка)",
    day7Breakfast7: "Банан – 80 г",
    day7Breakfast8: "Зелене яблуко – 50 г",
    day7Breakfast9: "Натуральний йогурт – 120 г",
    day7BreakfastStep1: "Нарізати помідори і кріп",
    day7BreakfastStep2:
      "Збити яйця зі сметаною до однорідності, додати овочі та приготувати омлет",
    day7BreakfastStep3:
      "Подавати омлет з шматочком хліба, намазаного творожним сиром",
    day7BreakfastStep4: "Фрукти та йогурт – як додаток до сніданку",
    day7BreakfastNutrition1: "🔥 Калорії: ~560 ккал",
    day7BreakfastNutrition2: "🥩 Білки: ~28 г",
    day7BreakfastNutrition3: "🥑 Жири: ~18 г",
    day7BreakfastNutrition4: "🍞 Вуглеводи: ~75 г",
    day7Lunch: "🍲 Обід",
    day7Lunch1: "Яловичий бульйон – 220 мл",
    day7Lunch2: "Картопля – 50 г",
    day7Lunch3: "Шампіньйони – 50 г",
    day7Lunch4: "Перлова крупа – 60 г",
    day7Lunch5: "Курячі сердечка – 120 г",
    day7Lunch6: "Сметана 10% – 25 г",
    day7Lunch7: "Петрушка – 15 г",
    day7Lunch8: "Пшеничні слайси – 20 г (~2 шт.)",
    day7Lunch9: "Авокадо – 40 г",
    day7Lunch10: "Сир – 20 г",
    day7LunchStep1:
      "У бульйоні відварити картоплю з шампіньйонами – це перша страва",
    day7LunchStep2: "Перлову крупу відварити окремо",
    day7LunchStep3:
      "Курячі сердечка обсмажити без масла, залити сумішшю води, сметани і петрушки, протушкувати – друга страва",
    day7LunchStep4: "Слайси, авокадо та сир – як додаток до обіду",
    day7LunchNutrition1: "🔥 Калорії: ~580 ккал",
    day7LunchNutrition2: "🥩 Білки: ~45 г",
    day7LunchNutrition3: "🥑 Жири: ~25 г",
    day7LunchNutrition4: "🍞 Вуглеводи: ~55 г",
    day7Dinner: "🐟 Вечеря",
    day7Dinner1: "Філе або стейк лосося – 150 г",
    day7Dinner2: "Огірки – 150 г",
    day7Dinner3: "Помідори черрі – 150 г",
    day7Dinner4: "Листя салату – 30 г",
    day7Dinner5: "Цибуля червона – 20 г",
    day7Dinner6: "Оливкова олія – 10 мл",
    day7Dinner7: "Гірчиця діжонська – 1 ч. л.",
    day7Dinner8: "Сік лимона – 6 мл",
    day7Dinner9: "Кальмар – 80 г",
    day7Dinner10: "Кукурудза – 30 г",
    day7Dinner11: "Огірок – 50 г",
    day7Dinner12: "Сметана 10% – 15 г",
    day7DinnerStep1: "Рибу запекти або приготувати на грилі",
    day7DinnerStep2:
      "З овочів зробити салат, заправити сумішшю олії, лимонного соку та гірчиці",
    day7DinnerStep3:
      "Кальмар з кукурудзою та огірком подати з невеликою кількістю сметани – як додаток",
    day7DinnerNutrition1: "🔥 Калорії: ~669 ккал",
    day7DinnerNutrition2: "🥩 Білки: ~48 г",
    day7DinnerNutrition3: "🥑 Жири: ~41,6 г",
    day7DinnerNutrition4: "🍞 Вуглеводи: ~45 г",
    day5totalNutrition: "Загальний КБЖВ",
    day7TotalNutrition1: "🔥 Калорії: ~1809 ккал",
    day7TotalNutrition2: "🥩 Білки: ~121 г",
    day7TotalNutrition3: "🥑 Жири: ~84,6 г",
    day7TotalNutrition4: "🍞 Вуглеводи: ~140 г",
    day8Title: "День восьмий",
    day8Breakfast: "🍽 Сніданок",
    composition: "Склад",
    day8Breakfast1: "Яйця – 2 шт.",
    day8Breakfast2: "Сметана 15% – 30 г",
    day8Breakfast3: "Помідори – 80 г",
    day8Breakfast4: "Зелена цибуля – 10 г",
    day8Breakfast5: "Зерновий хліб – 30 г (~1 шматок)",
    day8Breakfast6: "Банан – 80 г",
    day8Breakfast7: "Йогурт натуральний – 120 г",
    howToCook: "Як приготувати",
    day8BreakfastStep1: "Нарізати помідори та зелень",
    day8BreakfastStep2:
      "Збити яйця зі сметаною, змішати з овочами і приготувати омлет на сковороді",
    day8BreakfastStep3: "Подавати з шматочком хліба, йогуртом і бананом",
    nutrition: "КБЖВ",
    day8BreakfastNutrition1: "🔥 Калорії: ~520 ккал",
    day8BreakfastNutrition2: "🥩 Білки: ~25 г",
    day8BreakfastNutrition3: "🥑 Жири: ~20 г",
    day8BreakfastNutrition4: "🍞 Вуглеводи: ~65 г",
    day8Lunch: "🍲 Обід",
    day8Lunch1: "Курячий бульйон – 220 мл",
    day8Lunch2: "Куряче філе – 120 г",
    day8Lunch3: "Рис жасмин – 60 г",
    day8Lunch4: "Морква – 40 г",
    day8Lunch5: "Цибуля – 20 г",
    day8Lunch6: "Творог 1% – 100 г",
    day8Lunch7: "Вівсяне молоко – 100 мл",
    day8Lunch8: "Яблуко – 100 г",
    day8LunchStep1: "Приготувати суп на курячому бульйоні з овочами",
    day8LunchStep2:
      "Відварити рис. Обсмажити або запекти куряче філе з морквою і цибулею",
    day8LunchStep3:
      "Для десерту: змішати творог з вівсяним молоком та нарізаним яблуком",
    day8LunchNutrition1: "🔥 Калорії: ~720 ккал",
    day8LunchNutrition2: "🥩 Білки: ~60 г",
    day8LunchNutrition3: "🥑 Жири: ~20 г",
    day8LunchNutrition4: "🍞 Вуглеводи: ~85 г",
    day8Dinner: "🐟 Вечеря",
    day8Dinner1: "Філе лосося – 150 г",
    day8Dinner2: "Листя салату – 30 г",
    day8Dinner3: "Огірки та томати черрі – 150 г",
    day8Dinner4: "Червона цибуля – 20 г",
    day8Dinner5: "Оливкова олія – 10 мл",
    day8Dinner6: "Сік лимона – 6 мл",
    day8DinnerStep1: "Рибу запекти або приготувати на грилі",
    day8DinnerStep2:
      "Нарізати овочі, змішати з листям салату та заправити олією і лимонним соком",
    day8DinnerNutrition1: "🔥 Калорії: ~570 ккал",
    day8DinnerNutrition2: "🥩 Білки: ~36 г",
    day8DinnerNutrition3: "🥑 Жири: ~22 г",
    day8DinnerNutrition4: "🍞 Вуглеводи: ~45 г",
    day8totalNutrition: "Загальний КБЖВ дня 8",
    day8TotalNutrition1: "🔥 Калорії: ~1810 ккал",
    day8TotalNutrition2: "🥩 Білки: ~121 г",
    day8TotalNutrition3: "🥑 Жири: ~62 г",
    day8TotalNutrition4: "🍞 Вуглеводи: ~195 г",
    day9Title: "День девятий",
    day9Breakfast: "🍽 Сніданок",
    day9Breakfast1: "Яйця – 3 шт.",
    day9Breakfast2: "Сметана 10% – 30 г",
    day9Breakfast3: "Твердий сир – 20 г",
    day9Breakfast4: "Помідори – 80 г",
    day9Breakfast5: "Зерновий хліб – 30 г (~1 скибка)",
    day9Breakfast6: "Банан – 80 г",
    day9Breakfast7: "Йогурт натуральний – 100 г",
    day9BreakfastStep1:
      "Збити яйця зі сметаною та натертим сиром, приготувати омлет",
    day9BreakfastStep2:
      "Подавати з нарізаними помідорами, хлібом та йогуртом з бананом",
    day9BreakfastNutrition1: "🔥 Калорії: ~540 ккал",
    day9BreakfastNutrition2: "🥩 Білки: ~28 г",
    day9BreakfastNutrition3: "🥑 Жири: ~22 г",
    day9BreakfastNutrition4: "🍞 Вуглеводи: ~60 г",

    day9Lunch: "🍲 Обід",
    day9Lunch1: "Яловичий бульйон – 220 мл",
    day9Lunch2: "Картопля – 100 г",
    day9Lunch3: "Шампіньйони – 50 г",
    day9Lunch4: "Перлова крупа – 60 г",
    day9Lunch5: "Курячі сердечка – 120 г",
    day9Lunch6: "Сметана 10% – 25 г",
    day9Lunch7: "Петрушка – 15 г",
    day9Lunch8: "Авокадо – 40 г",
    day9Lunch9: "Пшеничні слайси – 20 г",
    day9Lunch10: "Твердий сир – 20 г",
    day9LunchStep1: "Для супу: відварити картоплю з грибами на бульйоні",
    day9LunchStep2:
      "Для другої страви: обсмажити сердечка без масла, додати воду зі сметаною та зеленню, тушкувати",
    day9LunchStep3: "Перловку відварити окремо",
    day9LunchStep4: "Подавати з хлібом, авокадо та сиром",
    day9LunchNutrition1: "🔥 Калорії: ~720 ккал",
    day9LunchNutrition2: "🥩 Білки: ~55 г",
    day9LunchNutrition3: "🥑 Жири: ~30 г",
    day9LunchNutrition4: "🍞 Вуглеводи: ~80 г",

    day9Dinner: "🐟 Вечеря",
    day9Dinner1: "Стейк лосося – 150 г",
    day9Dinner2: "Огірки – 50 г",
    day9Dinner3: "Помідори чері – 100 г",
    day9Dinner4: "Листя салату – 30 г",
    day9Dinner5: "Оливкова олія – 10 мл",
    day9Dinner6: "Гірчиця діжонська – 1 ч. л.",
    day9Dinner7: "Сік лимона – 6 мл",
    day9Dinner8: "Кальмар – 80 г",
    day9Dinner9: "Кукурудза – 30 г",
    day9Dinner10: "Огірок – 50 г",
    day9Dinner11: "Сметана 10% – 15 г",
    day9DinnerStep1: "Рибу запекти або приготувати на грилі",
    day9DinnerStep2:
      "Зробити салат із овочів, заправити маслом, гірчицею та лимонним соком",
    day9DinnerStep3:
      "Кальмар із кукурудзою та огірком трохи змішати зі сметаною як додатковий перекус",
    day9DinnerNutrition1: "🔥 Калорії: ~550 ккал",
    day9DinnerNutrition2: "🥩 Білки: ~38 г",
    day9DinnerNutrition3: "🥑 Жири: ~32,6 г",
    day9DinnerNutrition4: "🍞 Вуглеводи: ~50 г",

    day9totalNutrition: "Загальний КБЖВ Дня 9",
    day9TotalNutrition1: "🔥 Калорії: ~1810 ккал",
    day9TotalNutrition2: "🥩 Білки: ~121 г",
    day9TotalNutrition3: "🥑 Жири: ~84,6 г",
    day9TotalNutrition4: "🍞 Вуглеводи: ~190 г",

    title: "Калькулятор калорій",
    mainTitle: "Калькулятор калорій",
    gender: "Стать:",
    male: "Чоловік",
    female: "Жінка",
    age: "Вік:",
    height: "Зріст (см):",
    weight: "Вага (кг):",
    activity: "Рівень активності:",
    act1: "Мінімальний (сидяча робота)",
    act2: "Легка активність (1-3 рази/тиждень)",
    act3: "Середня (3-5 разів/тиждень)",
    act4: "Висока (6-7 разів/тиждень)",
    act5: "Дуже висока (спорт щодня)",
    calculate: "Розрахувати",
    resultTitle: "Ваш результат:",
    maintainLabel: "Підтримка ваги:",
    lossLabel: "Для схуднення:",
    gainLabel: "Для набору:",
    kcal: "ккал/день"
  },
  ru: {
    logo: "Марафон Трансформации",
    hedernavtext1: "Основная часть",
    hedernavtext2: "Рацион",
    hedernavtext3: "Расчет нормы КБЖУ",
    // aboutMaraphonTitle1: "«9 дней, которые могут изменить твою жизнь»",
    // aboutMaraphonText1:
    //   "Идеальное сочетание системного подхода в трёх сферах:\n✅ Деньги и блокирующие установки\n✅ Тело как отражение души\n✅ Продажи через Instagram",
    aboutMaraphonButton: "Расчет нормы КБЖУ",
    aboutMaraphonTitleMain: "🔥 Марафон перемен: тело, которое слушается тебя",
    aboutMaraphonSubtitle: "14 дней — чтобы увидеть реальные изменения.",
    aboutMaraphonDescription1: "Ты получишь не мотивационные лозунги, а систему, которая работает: четкое меню, сбалансированный рацион, практические советы и поддержку, чтобы тело начало слушаться тебя с первой недели.",
    aboutMaraphonDescription2: "Никаких диет, истощения или «срывов». Ты научишься правильно питаться, иметь энергию и видеть, как вес реагирует на твою последовательность, а не на случайность.",
    aboutMaraphonPoint1: " минус 2–4 кг за 14 дней без стресса",
    aboutMaraphonPoint2: " восстановление режима сна и питания",
    aboutMaraphonPoint3: " новая лёгкость в теле и голове",
    aboutMaraphonPoint4: " сила воли без надрыва",
    aboutMaraphonConclusion1: "Это не марафон ради цифр — это старт новой дисциплины, где забота о себе становится формой благодарности за жизнь.",
    aboutMaraphonConclusion2: "Твоё тело умеет слушаться. Ему просто нужно, чтобы ты наконец заговорил с ним на одном языке.",
    dayText: "Как приготовить? Состав. КБЖУ.",
    dayButton: "К меню",
    aboutMaraphonButton2: "вернуться на главную страницу",
    forWhomTitle: "Для кого марафон",
    forWhom1: "Хочешь привести тело в порядок, улучшить фигуру и питание.",
    forWhom2: "Хочешь взять ответственность за жизнь и перестать откладывать.",
    forWhom3:
      "Хочешь зарабатывать и реализовываться через Instagram и другие возможности.",
    forWhom4: "Готов развиваться системно и менять привычки на практике.",
    forWhomText:
      "Чувствуешь, что можешь больше — зарабатывать больше, быть энергичнее, сильнее, продуктивнее.",

    aboutAuthorsTitle: "Об авторе",
    aboutAuthorsText:
      "Сергей Чертилин — ведущий марафона, миссионер и автор многих проектов по личной трансформации и самореализации. Прошел путь от 140 кг до минус 55 кг, полностью изменив тело, привычки и подход к жизни. Знает, как выстраивать дисциплину, управлять собой и достигать целей на практике.",

    programTitle: "Программа",
    program1: "9 дней совместной работы",
    program2: "3 главные темы для самосовершенствования и личностного роста",
    program3: "4 встречи в прямом эфире",
    program4: "6 эффективных заданий",

    day1Title: "День первый",
    day1Breakfast: "🍽 Завтрак",
    composition: "Состав:",
    howToCook: "Как приготовить:",
    nutrition: "КБЖУ (на порцию):",

    day1Breakfast1: "Овсяная крупа – 50 г",
    day1Breakfast2: "Молоко 3,2% – 50 мл",
    day1Breakfast3: "Вода – 100 мл",
    day1Breakfast4: "Сливочное масло – 6 г",
    day1Breakfast5: "Курага – 15 г",
    day1Breakfast6: "Чернослив – 15 г",
    day1Breakfast7: "Изюм – 15 г",
    day1Breakfast8: "Куриное яйцо – 1 шт.",
    day1Breakfast9: "Банан – 120 г",
    day1Breakfast10: "Греческий йогурт без добавок – 140 г",

    day1BreakfastStep1: "Сварите кашу на воде и молоке.",
    day1BreakfastStep2: "Добавьте масло и сухофрукты.",
    day1BreakfastStep3: "Яйцо отварите или обжарьте без масла.",
    day1BreakfastStep4:
      "Подайте кашу с яйцом, а в качестве десерта – банан с йогуртом.",

    day1BreakfastNutrition1: "🔥 Калории: ~656 ккал",
    day1BreakfastNutrition2: "🥩 Белки: ~31,4 г",
    day1BreakfastNutrition3: "🥑 Жиры: ~16,4 г",
    day1BreakfastNutrition4: "🍞 Углеводы: ~93 г",

    day1Lunch: "🍲 Обед",
    day1Lunch1: "Куриный бульон – 250 мл (можно без него)",
    day1Lunch2: "Яичная лапша – 45 г",
    day1Lunch3: "Куриное филе – 140 г",
    day1Lunch4: "Помидоры – 100 г",
    day1Lunch5: "Огурцы – 100 г",
    day1Lunch6: "Салат айсберг – 30 г",
    day1Lunch7: "Оливковое масло – 7 мл",
    day1Lunch8: "Ряженка 1% – 120 мл",
    day1Lunch9: "Грецкие орехи – 30 г (~5 шт.)",

    day1LunchStep1: "Сварите лёгкий суп из бульона и лапши.",
    day1LunchStep2: "Запеките куриное филе со специями.",
    day1LunchStep3: "Сделайте овощной салат и заправьте оливковым маслом.",
    day1LunchStep4: "В качестве дополнения – ряженка с орехами.",

    day1LunchNutrition1: "🔥 Калории: ~786 ккал",
    day1LunchNutrition2: "🥩 Белки: ~64,2 г",
    day1LunchNutrition3: "🥑 Жиры: ~35,3 г",
    day1LunchNutrition4: "🍞 Углеводы: ~49,2 г",

    day1Dinner: "🍳 Ужин",
    day1Dinner1: "Яйцо – 2 шт.",
    day1Dinner2: "Яичный белок – 2 шт.",
    day1Dinner3: "Шпинат – 30 г",
    day1Dinner4: "Шампиньоны – 50 г",
    day1Dinner5: "Сливочное масло – 5 г",
    day1Dinner6: "Помидоры – 100 г",
    day1Dinner7: "Огурцы – 100 г",
    day1Dinner8: "Салат айсберг – 30 г",
    day1Dinner9: "Оливковое масло – 3 мл",
    day1Dinner10: "Лимонный сок – 3 мл",
    day1Dinner11: "Морская капуста – 60 г",
    day1Dinner12: "Креветки – 80 г",
    day1Dinner13: "Морковь (соломкой) – 50 г",
    day1Dinner14: "Кукуруза – 20 г",

    day1DinnerStep1:
      "Приготовьте яичницу с яйцами и белками, шпинатом и шампиньонами на сливочном масле.",
    day1DinnerStep2:
      "Сделайте овощной салат и заправьте оливковым маслом и лимонным соком.",
    day1DinnerStep3:
      "Отварите креветки и смешайте их с морской капустой, морковью и кукурузой.",

    day1DinnerNutrition1: "🔥 Калории: ~459 ккал",
    day1DinnerNutrition2: "🥩 Белки: ~44,1 г",
    day1DinnerNutrition3: "🥑 Жиры: ~21,3 г",
    day1DinnerNutrition4: "🍞 Углеводы: ~24 г",
    day2Title: "День второй",
    day2Breakfast: "🍽 Завтрак",
    composition: "Состав:",
    howToCook: "Как приготовить:",
    nutrition: "КБЖУ (на порцию):",

    day2Breakfast1: "Гречка (сухая) – 70 г",
    day2Breakfast2: "Сливочное масло – 8 г",
    day2Breakfast3: "Твёрдый сыр – 30 г",
    day2Breakfast4: "Хлеб бородинский – 20 г (~1 ломтик)",
    day2Breakfast5: "Рисовые хлебцы – 20 г (~2 шт.)",
    day2Breakfast6: "Арахисовая паста – 14 г",
    day2Breakfast7: "Банан – 45 г",
    day2Breakfast8: "Кофе – 200 мл",
    day2Breakfast9: "Горький шоколад – 5 г",

    day2BreakfastStep1:
      "Залить гречку кипятком и настоять или сварить, перед подачей добавить сливочное масло.",
    day2BreakfastStep2: "Сделать бутерброд: хлеб + сыр.",
    day2BreakfastStep3:
      "Приготовить рисовые хлебцы с арахисовой пастой и бананом.",
    day2BreakfastStep4: "Подать с кофе и кусочком шоколада.",

    day2BreakfastNutrition1: "🔥 Калории: ~716 ккал",
    day2BreakfastNutrition2: "🥩 Белки: ~28,5 г",
    day2BreakfastNutrition3: "🥑 Жиры: ~30,6 г",
    day2BreakfastNutrition4: "🍞 Углеводы: ~83,2 г",

    day2Lunch: "🍲 Обед",
    day2Lunch1: "Картофель – 180 г",
    day2Lunch2: "Куриная печень – 140 г",
    day2Lunch3: "Лук – 50 г",
    day2Lunch4: "Сметана 10% – 30 г",
    day2Lunch5: "Подсолнечное масло – 7 мл",
    day2Lunch6: "Хлеб бородинский – 30 г (~1 кусок)",
    day2Lunch7: "Авокадо – 40 г",
    day2Lunch8: "Сёмга слабосолёная – 30 г",

    day2LunchStep1: "Отварить или запечь картофель.",
    day2LunchStep2:
      "Печень обжарить с луком, потом потушить в смеси сметаны, воды и специй.",
    day2LunchStep3:
      "Приготовить тост: хлеб + размятый авокадо + кусочки сёмги.",

    day2LunchNutrition1: "🔥 Калории: ~680 ккал",
    day2LunchNutrition2: "🥩 Белки: ~41,9 г",
    day2LunchNutrition3: "🥑 Жиры: ~29,7 г",
    day2LunchNutrition4: "🍞 Углеводы: ~65,8 г",

    day2Dinner: "🍳 Ужин",
    day2Dinner1: "Яйца – 2 шт.",
    day2Dinner2: "Молоко 2,5% – 150 мл",
    day2Dinner3: "Сыр – 40 г",
    day2Dinner4: "Помидор – 50 г",
    day2Dinner5: "Кефир 1% – 250 мл",
    day2Dinner6: "Немного корицы (по желанию)",

    day2DinnerStep1: "Смешать яйца, молоко, сыр и нарезанный помидор.",
    day2DinnerStep2:
      "Взбить смесь и готовить 2–2,5 минуты в микроволновке или на сковороде/в духовке.",
    day2DinnerStep3: "Подать белковый омлет, а к ужину выпить кефир с корицей.",

    day2DinnerNutrition1: "🔥 Калории: ~406 ккал",
    day2DinnerNutrition2: "🥩 Белки: ~30,6 г",
    day2DinnerNutrition3: "🥑 Жиры: ~17,4 г",
    day2DinnerNutrition4: "🍞 Углеводы: ~22,8 г",

    day2Summary: "📊 Итог за день (День 2)",
    day2SummaryCalories: "🔥 Калории: ~1802 ккал",
    day2SummaryProteins: "🥩 Белки: ~101 г",
    day2SummaryFats: "🥑 Жиры: ~87,7 г",
    day2SummaryCarbs: "🍞 Углеводы: ~151,8 г",
    day3Title: "День третий",
    day3Breakfast: "🍽 Завтрак",
    day3Lunch: "🍲 Обед",
    day3Dinner: "🐟 Ужин",
    composition: "Состав:",
    howToCook: "Как приготовить:",
    nutrition: "КБЖУ:",

    day3Breakfast1: "Хлопья овсяные – 50 г",
    day3Breakfast2: "Молоко – 40 мл",
    day3Breakfast3: "Яйцо – 1 шт.",
    day3Breakfast4: "Какао – 10 г",
    day3Breakfast5: "Киви – 60 г",
    day3Breakfast6: "Паста кокосовая – 12 г",
    day3Breakfast7: "Апельсин – 80 г",
    day3Breakfast8: "Груша – 80 г",
    day3Breakfast9: "Яблоко – 80 г",
    day3Breakfast10: "Сметана 10% – 30 г",
    day3Breakfast11: "Кедровые орехи – 15 г",
    day3BreakfastStep1:
      "Взбить молоко с яйцом до однородности, добавить хлопья и какао, оставить на 7 минут для набухания.",
    day3BreakfastStep2:
      "Обжарить с двух сторон овсяноблин, смазать пастой и положить киви, свернуть.",
    day3BreakfastStep3:
      "Нарезать фрукты, соединить с сметаной и посыпать кедровыми орехами.",
    day3BreakfastNutrition1: "🔥 Калории: ~498 ккал",
    day3BreakfastNutrition2: "🥩 Белки: ~17,2 г",
    day3BreakfastNutrition3: "🥑 Жиры: ~18,6 г",
    day3BreakfastNutrition4: "🍞 Углеводы: ~63,7 г",

    day3Lunch1: "Мясной бульон – 220 мл (по желанию можно убрать)",
    day3Lunch2: "Квашеная капуста – 100 г",
    day3Lunch3: "Макароны ц/з – 50 г",
    day3Lunch4: "Свиной фарш – 90 г",
    day3Lunch5: "Лук – 40 г",
    day3Lunch6: "Томатная паста – 30 г",
    day3Lunch7: "Фундук – 20 г (~20 шт.)",
    day3Lunch8: "Сушёный инжир – 3 шт. (~30 г)",
    day3LunchStep1: "Приготовить щи на мясном бульоне.",
    day3LunchStep2:
      "Для второго блюда обжарить фарш с луком, добавить томатную пасту и воду, потушить.",
    day3LunchStep3: "Отварить макароны и смешать с фаршем.",
    day3LunchNutrition1: "🔥 Калории: ~790 ккал",
    day3LunchNutrition2: "🥩 Белки: ~32,8 г",
    day3LunchNutrition3: "🥑 Жиры: ~37,1 г",
    day3LunchNutrition4: "🍞 Углеводы: ~73,9 г",

    day3Dinner1: "Филе хека – 150 г",
    day3Dinner2: "Брокколи – 70 г",
    day3Dinner3: "Цветная капуста – 100 г",
    day3Dinner4: "Сливки 20% – 30 мл",
    day3Dinner5: "Оливки – 20 г",
    day3Dinner6: "Квашеная капуста – 50 г",
    day3Dinner7: "Масло оливы – 5 мл",
    day3Dinner8: "Творог мягкий обезжиренный – 170 г",
    day3Dinner9: "Огурец – 40 г",
    day3Dinner10: "Укроп – 10 г",
    day3Dinner11: "Зелёный лук – 10 г",
    day3DinnerStep1:
      "Запечь рыбу с брокколи и цветной капустой в сливках с водой.",
    day3DinnerStep2:
      "Выложить на тарелку с оливками и квашеной капустой, заправленной маслом.",
    day3DinnerStep3: "Нарезать огурец и зелень, перемешать с творогом.",
    day3DinnerNutrition1: "🔥 Калории: ~513 ккал",
    day3DinnerNutrition2: "🥩 Белки: ~53,2 г",
    day3DinnerNutrition3: "🥑 Жиры: ~27,3 г",
    day3DinnerNutrition4: "🍞 Углеводы: ~27,0 г",
    day4Title: "День четвёртый",
    day4Breakfast: "🍽 Завтрак",
    composition: "Состав:",
    howToCook: "Как приготовить:",
    nutrition: "КБЖУ:",

    day4Breakfast1: "Молоко 3,2% – 160 мл",
    day4Breakfast2: "Банан – 80 г",
    day4Breakfast3: "Творог 5% – 100 г",
    day4Breakfast4: "Цветочный мед – 15 г",
    day4Breakfast5: "Зелёное яблоко – 120 г",

    day4BreakfastStep1: "Нарезать банан.",
    day4BreakfastStep2:
      "Взбить банан, молоко, творог и мед в блендере до однородности.",
    day4BreakfastStep3: "Нарезать яблоко отдельно, подать к смузи.",

    day4BreakfastNutrition1: "🔥 Калории: ~465 ккал",
    day4BreakfastNutrition2: "🥩 Белки: ~28 г",
    day4BreakfastNutrition3: "🥑 Жиры: ~12 г",
    day4BreakfastNutrition4: "🍞 Углеводы: ~68 г",

    day4Lunch: "🍲 Обед",
    day4Lunch1: "Кабачки – 80 г",
    day4Lunch2: "Цветная капуста – 80 г",
    day4Lunch3: "Лук – 50 г",
    day4Lunch4: "Шпинат – 40 г",
    day4Lunch5: "Сливки 20% – 30 мл",
    day4Lunch6: "Гречка сухая – 60 г",
    day4Lunch7: "Шампиньоны – 120 г",
    day4Lunch8: "Морковь – 30 г",
    day4Lunch9: "Сливочное масло – 7 г",
    day4Lunch10: "Подсолнечное масло – 4 г",
    day4Lunch11: "Слайсы пшеничные – 20 г",
    day4Lunch12: "Урбеч из семян льна – 10 г",
    day4Lunch13: "Сыр адыгейский – 30 г",

    day4LunchStep1:
      "Сделать крем-суп из кабачков, цветной капусты, лука и шпината с добавлением сливок.",
    day4LunchStep2:
      "Сварить гречку, обжарить грибы с морковью на масле, смешать с гречкой.",
    day4LunchStep3: "Сделать бутерброды: намазать урбеч на хлеб, добавить сыр.",

    day4LunchNutrition1: "🔥 Калории: ~600 ккал",
    day4LunchNutrition2: "🥩 Белки: ~34 г",
    day4LunchNutrition3: "🥑 Жиры: ~23 г",
    day4LunchNutrition4: "🍞 Углеводы: ~70 г",

    day4Dinner: "🐟 Ужин",
    day4Dinner1: "Филе индейки – 120 г",
    day4Dinner2: "Болгарский перец – 150 г",
    day4Dinner3: "Лук – 50 г",
    day4Dinner4: "Сметана 15% – 20 г",
    day4Dinner5: "Томатная паста – 20 г",
    day4Dinner6: "Огурцы – 100 г",
    day4Dinner7: "Помидоры – 100 г",
    day4Dinner8: "Зелёная редька – 50 г",
    day4Dinner9: "Фасоль стручковая – 80 г",
    day4Dinner10: "Салат – 15 г",
    day4Dinner11: "Оливковое масло – 7 мл",
    day4Dinner12: "Сок лимона – 3 мл",
    day4Dinner13: "Белки яиц – 4 шт.",

    day4DinnerStep1:
      "Тушить индейку с перцем, луком, томатной пастой и сметаной до готовности.",
    day4DinnerStep2: "Сварить фасоль и яйца, нарезать.",
    day4DinnerStep3:
      "Сделать салат: смешать фасоль, яйца, огурцы, помидоры, редьку и салат, заправить маслом и соком лимона.",
    day4DinnerStep4: "Подать мясо с тушеными овощами и салатом.",

    day4DinnerNutrition1: "🔥 Калории: ~727 ккал",
    day4DinnerNutrition2: "🥩 Белки: ~61 г",
    day4DinnerNutrition3: "🥑 Жиры: ~26,1 г",
    day4DinnerNutrition4: "🍞 Углеводы: ~48,4 г",
    day5Title: "День пятый",
    day5Breakfast: "🍽 Завтрак",
    day5Lunch: "🍲 Обед",
    day5Dinner: "🐟 Ужин",
    composition: "Состав:",
    howToCook: "Как приготовить:",
    nutrition: "КБЖУ:",

    // Завтрак
    day5Breakfast1: "Пшено – 70 г",
    day5Breakfast2: "Молоко 3,2% – 120 мл",
    day5Breakfast3: "Вода – 160 мл",
    day5Breakfast4: "Груша – 60 г",
    day5Breakfast5: "Кедровые орехи – 5 г",
    day5Breakfast6: "Сливочное масло – 5 г",
    day5Breakfast7: "Зеленое яблоко – 140 г",
    day5Breakfast8: "Твердый сыр – 35 г",
    day5BreakfastStep1:
      "Сварить пшено на смеси воды и молока до готовности, добавить масло.",
    day5BreakfastStep2:
      "Нарезать грушу и выложить сверху каши, посыпать кедровыми орехами.",
    day5BreakfastStep3: "Яблоко нарезать и подать вместе с твердым сыром.",
    day5BreakfastNutrition1: "🔥 Калории: ~540 ккал",
    day5BreakfastNutrition2: "🥩 Белки: ~22 г",
    day5BreakfastNutrition3: "🥑 Жиры: ~16 г",
    day5BreakfastNutrition4: "🍞 Углеводы: ~72 г",

    // Обед
    day5Lunch1: "Куриный бульон – 220 мл (по желанию)",
    day5Lunch2: "Смесь овощей (замороженная) – 120 г",
    day5Lunch3: "Жасминовый рис – 30 г",
    day5Lunch4: "Куриный фарш – 115 г",
    day5Lunch5: "Лук – 20 г",
    day5Lunch6: "Морковь – 20 г",
    day5Lunch7: "Яйцо – 1 шт.",
    day5Lunch8: "Творог 1% – 110 г",
    day5Lunch9: "Овсяное молоко – 110 мл",
    day5Lunch10: "Банан – 80 г",
    day5LunchStep1:
      "На курином бульоне приготовить овощной суп с замороженными овощами.",
    day5LunchStep2:
      "Отварить рис. Сделать котлеты: смешать фарш с луком, морковью и яйцом, приправить, обжарить или запечь.",
    day5LunchStep3:
      "Для белково-углеводного напитка: смешать творог, овсяное молоко и банан в блендере.",
    day5LunchNutrition1: "🔥 Калории: ~700 ккал",
    day5LunchNutrition2: "🥩 Белки: ~55 г",
    day5LunchNutrition3: "🥑 Жиры: ~20 г",
    day5LunchNutrition4: "🍞 Углеводы: ~80 г",

    // Ужин
    day5Dinner1: "Консервированный тунец – 150 г",
    day5Dinner2: "Помидор – 100 г",
    day5Dinner3: "Сыр пармезан – 30 г",
    day5Dinner4: "Базилик – 15 г",
    day5Dinner5: "Красный лук – 30 г",
    day5Dinner6: "Сладкий перец – 80 г",
    day5Dinner7: "Оливковое масло – 7 мл",
    day5Dinner8: "Клубника – 100 г",
    day5Dinner9: "Греческий йогурт 2% – 140 г",
    day5DinnerStep1:
      "Нарезать сладкий перец, помидор, лук и выложить на тарелку с базиликом.",
    day5DinnerStep2:
      "Добавить тунец, посыпать тертым пармезаном, заправить маслом.",
    day5DinnerStep3:
      "Клубнику смешать с йогуртом как десерт или дополнение к салату.",
    day5DinnerNutrition1: "🔥 Калории: ~569 ккал",
    day5DinnerNutrition2: "🥩 Белки: ~59 г",
    day5DinnerNutrition3: "🥑 Жиры: ~28 г",
    day5DinnerNutrition4: "🍞 Углеводы: ~64,1 г",

    // Итог
    day5totalNutrition: "Общий КБЖУ:",
    day5TotalNutrition1: "🔥 Калории: ~1809 ккал",
    day5TotalNutrition2: "🥩 Белки: ~136 г",
    day5TotalNutrition3: "🥑 Жиры: ~64 г",
    day5TotalNutrition4: "🍞 Углеводы: ~165,1 г",
    day6Title: "День шестой",

    day6Breakfast: "🍽 Завтрак",
    composition: "Состав",
    day6Breakfast1: "Овсяные хлопья (долгая варка) – 30 г",
    day6Breakfast2: "Молоко 3,2% – 200 мл",
    day6Breakfast3: "Ряженка 1% – 100 мл",
    day6Breakfast4: "Семечки подсолнуха – 10 г",
    day6Breakfast5: "Клубника – 100 г",
    day6Breakfast6: "Цветочный мед – 15 г",
    howToCook: "Как приготовить",
    day6BreakfastStep1:
      "Залить хлопья молоком и ряженкой, довести до готовности",
    day6BreakfastStep2: "Добавить нарезанную клубнику, посыпать семечками",
    day6BreakfastStep3: "Полить медом и подать",
    nutrition: "КБЖУ",
    day6BreakfastNutrition1: "🔥 Калории: ~540 ккал",
    day6BreakfastNutrition2: "🥩 Белки: ~22 г",
    day6BreakfastNutrition3: "🥑 Жиры: ~16 г",
    day6BreakfastNutrition4: "🍞 Углеводы: ~72 г",

    day6Lunch: "🍲 Обед",
    day6Lunch1: "Куриный бульон – 220 мл",
    day6Lunch2: "Смесь овощей (замороженная) – 120 г",
    day6Lunch3: "Рис жасмин – 30 г",
    day6Lunch4: "Куриный фарш – 115 г",
    day6Lunch5: "Лук – 20 г",
    day6Lunch6: "Морковь – 20 г",
    day6Lunch7: "Яйцо – 1 шт",
    day6Lunch8: "Творог 1% – 110 г",
    day6Lunch9: "Овсяное молоко – 110 мл",
    day6Lunch10: "Банан – 80 г",
    day6LunchStep1: "На бульоне приготовить овощной суп",
    day6LunchStep2:
      "Сварить рис. Сделать котлеты: смешать фарш с луком, морковью и яйцом, приправить солью и перцем, обжарить или запечь",
    day6LunchStep3:
      "Белково-углеводный напиток: смешать творог, овсяное молоко и банан в блендере",
    day6LunchNutrition1: "🔥 Калории: ~700 ккал",
    day6LunchNutrition2: "🥩 Белки: ~55 г",
    day6LunchNutrition3: "🥑 Жиры: ~20 г",
    day6LunchNutrition4: "🍞 Углеводы: ~80 г",

    day6Dinner: "🐟 Ужин",
    day6Dinner1: "Консервированный тунец – 150 г",
    day6Dinner2: "Помидор – 100 г",
    day6Dinner3: "Сыр пармезан – 30 г",
    day6Dinner4: "Базилик – 15 г",
    day6Dinner5: "Красный лук – 30 г",
    day6Dinner6: "Сладкий перец – 80 г",
    day6Dinner7: "Оливковое масло – 7 мл",
    day6Dinner8: "Клубника – 100 г",
    day6Dinner9: "Греческий йогурт 2% – 140 г",
    day6DinnerStep1:
      "Нарезать перец, помидор, лук, выложить на тарелку с базиликом",
    day6DinnerStep2:
      "Добавить тунец, посыпать тертым пармезаном, заправить оливковым маслом",
    day6DinnerStep3:
      "Клубнику смешать с йогуртом как десерт или дополнение к салату",
    day6DinnerNutrition1: "🔥 Калории: ~569 ккал",
    day6DinnerNutrition2: "🥩 Белки: ~59 г",
    day6DinnerNutrition3: "🥑 Жиры: ~28 г",
    day6DinnerNutrition4: "🍞 Углеводы: ~64,1 г",

    day5totalNutrition: "Общий КБЖУ",
    day6TotalNutrition1: "🔥 Калории: ~1809 ккал",
    day6TotalNutrition2: "🥩 Белки: ~136 г",
    day6TotalNutrition3: "🥑 Жиры: ~64 г",
    day6TotalNutrition4: "🍞 Углеводы: ~165,1 г",
    day7Title: "День седьмой",
    day7Breakfast: "🍽 Завтрак",
    composition: "Состав",
    howToCook: "Как приготовить",
    nutrition: "КБЖУ",
    day7Breakfast1: "Яйца – 3 шт.",
    day7Breakfast2: "Сметана 15% – 30 г",
    day7Breakfast3: "Укроп – 15 г",
    day7Breakfast4: "Помидоры – 80 г",
    day7Breakfast5: "Творожный сыр – 10 г",
    day7Breakfast6: "Зерновой хлеб – 30 г (~1 ломтик)",
    day7Breakfast7: "Банан – 80 г",
    day7Breakfast8: "Зеленое яблоко – 50 г",
    day7Breakfast9: "Натуральный йогурт – 120 г",
    day7BreakfastStep1: "Нарезать помидоры и укроп",
    day7BreakfastStep2:
      "Взбить яйца со сметаной до однородности, добавить овощи и приготовить омлет",
    day7BreakfastStep3:
      "Подавать омлет с кусочком хлеба, намазанного творожным сыром",
    day7BreakfastStep4: "Фрукты и йогурт – как дополнение к завтраку",
    day7BreakfastNutrition1: "🔥 Калории: ~560 ккал",
    day7BreakfastNutrition2: "🥩 Белки: ~28 г",
    day7BreakfastNutrition3: "🥑 Жиры: ~18 г",
    day7BreakfastNutrition4: "🍞 Углеводы: ~75 г",
    day7Lunch: "🍲 Обед",
    day7Lunch1: "Говяжий бульон – 220 мл",
    day7Lunch2: "Картофель – 50 г",
    day7Lunch3: "Шампиньоны – 50 г",
    day7Lunch4: "Перловая крупа – 60 г",
    day7Lunch5: "Куриные сердечки – 120 г",
    day7Lunch6: "Сметана 10% – 25 г",
    day7Lunch7: "Петрушка – 15 г",
    day7Lunch8: "Пшеничные слайсы – 20 г (~2 шт.)",
    day7Lunch9: "Авокадо – 40 г",
    day7Lunch10: "Сыр – 20 г",
    day7LunchStep1:
      "В бульоне отварить картофель с шампиньонами – это первое блюдо",
    day7LunchStep2: "Перловую крупу отварить отдельно",
    day7LunchStep3:
      "Куриные сердечки обжарить без масла, залить смесью воды, сметаны и петрушки, потушить – второе блюдо",
    day7LunchStep4: "Слайсы, авокадо и сыр – как дополнение к обеду",
    day7LunchNutrition1: "🔥 Калории: ~580 ккал",
    day7LunchNutrition2: "🥩 Белки: ~45 г",
    day7LunchNutrition3: "🥑 Жиры: ~25 г",
    day7LunchNutrition4: "🍞 Углеводы: ~55 г",
    day7Dinner: "🐟 Ужин",
    day7Dinner1: "Филе или стейк лосося – 150 г",
    day7Dinner2: "Огурцы – 150 г",
    day7Dinner3: "Томаты черри – 150 г",
    day7Dinner4: "Листья салата – 30 г",
    day7Dinner5: "Лук красный – 20 г",
    day7Dinner6: "Оливковое масло – 10 мл",
    day7Dinner7: "Дижонская горчица – 1 ч. л.",
    day7Dinner8: "Сок лимона – 6 мл",
    day7Dinner9: "Кальмар – 80 г",
    day7Dinner10: "Кукуруза – 30 г",
    day7Dinner11: "Огурец – 50 г",
    day7Dinner12: "Сметана 10% – 15 г",
    day7DinnerStep1: "Рыбу запечь или приготовить на гриле",
    day7DinnerStep2:
      "Из овощей сделать салат, заправить смесью масла, лимонного сока и горчицы",
    day7DinnerStep3:
      "Кальмар с кукурузой и огурцом подать с небольшим количеством сметаны – как дополнение",
    day7DinnerNutrition1: "🔥 Калории: ~669 ккал",
    day7DinnerNutrition2: "🥩 Белки: ~48 г",
    day7DinnerNutrition3: "🥑 Жиры: ~41,6 г",
    day7DinnerNutrition4: "🍞 Углеводы: ~45 г",
    day5totalNutrition: "Общий КБЖУ",
    day7TotalNutrition1: "🔥 Калории: ~1809 ккал",
    day7TotalNutrition2: "🥩 Белки: ~121 г",
    day7TotalNutrition3: "🥑 Жиры: ~84,6 г",
    day7TotalNutrition4: "🍞 Углеводы: ~140 г",
    day8Title: "День восьмой",
    day8Breakfast: "🍽 Завтрак",
    composition: "Состав",
    day8Breakfast1: "Яйца – 2 шт.",
    day8Breakfast2: "Сметана 15% – 30 г",
    day8Breakfast3: "Помидоры – 80 г",
    day8Breakfast4: "Зеленый лук – 10 г",
    day8Breakfast5: "Зерновой хлеб – 30 г (~1 ломтик)",
    day8Breakfast6: "Банан – 80 г",
    day8Breakfast7: "Йогурт натуральный – 120 г",
    howToCook: "Как приготовить",
    day8BreakfastStep1: "Нарезать помидоры и зелень",
    day8BreakfastStep2:
      "Взбить яйца со сметаной, смешать с овощами и приготовить омлет на сковороде",
    day8BreakfastStep3: "Подавать с кусочком хлеба, йогуртом и бананом",
    nutrition: "КБЖУ",
    day8BreakfastNutrition1: "🔥 Калории: ~520 ккал",
    day8BreakfastNutrition2: "🥩 Белки: ~25 г",
    day8BreakfastNutrition3: "🥑 Жиры: ~20 г",
    day8BreakfastNutrition4: "🍞 Углеводы: ~65 г",
    day8Lunch: "🍲 Обед",
    day8Lunch1: "Куриный бульон – 220 мл",
    day8Lunch2: "Куриное филе – 120 г",
    day8Lunch3: "Рис жасмин – 60 г",
    day8Lunch4: "Морковь – 40 г",
    day8Lunch5: "Лук – 20 г",
    day8Lunch6: "Творог 1% – 100 г",
    day8Lunch7: "Овсяное молоко – 100 мл",
    day8Lunch8: "Яблоко – 100 г",
    day8LunchStep1: "Приготовить суп на курином бульоне с овощами",
    day8LunchStep2:
      "Отварить рис. Обжарить или запечь куриное филе с морковью и луком",
    day8LunchStep3:
      "Для десерта: смешать творог с овсяным молоком и нарезанным яблоком",
    day8LunchNutrition1: "🔥 Калории: ~720 ккал",
    day8LunchNutrition2: "🥩 Белки: ~60 г",
    day8LunchNutrition3: "🥑 Жиры: ~20 г",
    day8LunchNutrition4: "🍞 Углеводы: ~85 г",
    day8Dinner: "🐟 Ужин",
    day8Dinner1: "Филе лосося – 150 г",
    day8Dinner2: "Листья салата – 30 г",
    day8Dinner3: "Огурцы и томаты черри – 150 г",
    day8Dinner4: "Красный лук – 20 г",
    day8Dinner5: "Оливковое масло – 10 мл",
    day8Dinner6: "Сок лимона – 6 мл",
    day8DinnerStep1: "Рыбу запечь или приготовить на гриле",
    day8DinnerStep2:
      "Нарезать овощи, смешать с листьями салата и заправить маслом и лимонным соком",
    day8DinnerNutrition1: "🔥 Калории: ~570 ккал",
    day8DinnerNutrition2: "🥩 Белки: ~36 г",
    day8DinnerNutrition3: "🥑 Жиры: ~22 г",
    day8DinnerNutrition4: "🍞 Углеводы: ~45 г",
    day8totalNutrition: "ОБЩИЙ КБЖУ ДНЯ 8",
    day8TotalNutrition1: "🔥 Калории: ~1810 ккал",
    day8TotalNutrition2: "🥩 Белки: ~121 г",
    day8TotalNutrition3: "🥑 Жиры: ~62 г",
    day8TotalNutrition4: "🍞 Углеводы: ~195 г",
    day9Title: "День девятый",
    day9Breakfast: "🍽 Завтрак",
    day9Breakfast1: "Яйца – 3 шт.",
    day9Breakfast2: "Сметана 10% – 30 г",
    day9Breakfast3: "Твердый сыр – 20 г",
    day9Breakfast4: "Помидоры – 80 г",
    day9Breakfast5: "Зерновой хлеб – 30 г (~1 ломтик)",
    day9Breakfast6: "Банан – 80 г",
    day9Breakfast7: "Йогурт натуральный – 100 г",
    day9BreakfastStep1:
      "Взбить яйца со сметаной и натертым сыром, приготовить омлет",
    day9BreakfastStep2:
      "Подавать с нарезанными помидорами, хлебом и йогуртом с бананом",
    day9BreakfastNutrition1: "🔥 Калории: ~540 ккал",
    day9BreakfastNutrition2: "🥩 Белки: ~28 г",
    day9BreakfastNutrition3: "🥑 Жиры: ~22 г",
    day9BreakfastNutrition4: "🍞 Углеводы: ~60 г",

    day9Lunch: "🍲 Обед",
    day9Lunch1: "Говяжий бульон – 220 мл",
    day9Lunch2: "Картофель – 100 г",
    day9Lunch3: "Шампиньоны – 50 г",
    day9Lunch4: "Перловка – 60 г",
    day9Lunch5: "Куриные сердечки – 120 г",
    day9Lunch6: "Сметана 10% – 25 г",
    day9Lunch7: "Петрушка – 15 г",
    day9Lunch8: "Авокадо – 40 г",
    day9Lunch9: "Пшеничные слайсы – 20 г",
    day9Lunch10: "Твердый сыр – 20 г",
    day9LunchStep1: "Для супа: отварить картофель с грибами на бульоне",
    day9LunchStep2:
      "Для второго блюда: обжарить сердечки без масла, добавить воду со сметаной и зеленью, потушить",
    day9LunchStep3: "Перловку отварить отдельно",
    day9LunchStep4: "Подавать с хлебом, авокадо и сыром",
    day9LunchNutrition1: "🔥 Калории: ~720 ккал",
    day9LunchNutrition2: "🥩 Белки: ~55 г",
    day9LunchNutrition3: "🥑 Жиры: ~30 г",
    day9LunchNutrition4: "🍞 Углеводы: ~80 г",

    day9Dinner: "🐟 Ужин",
    day9Dinner1: "Стейк лосося – 150 г",
    day9Dinner2: "Огурцы – 50 г",
    day9Dinner3: "Томаты черри – 100 г",
    day9Dinner4: "Салатные листья – 30 г",
    day9Dinner5: "Оливковое масло – 10 мл",
    day9Dinner6: "Дижонская горчица – 1 ч. л.",
    day9Dinner7: "Лимонный сок – 6 мл",
    day9Dinner8: "Кальмар – 80 г",
    day9Dinner9: "Кукуруза – 30 г",
    day9Dinner10: "Огурец – 50 г",
    day9Dinner11: "Сметана 10% – 15 г",
    day9DinnerStep1: "Рыбу запечь или приготовить на гриле",
    day9DinnerStep2:
      "Сделать салат из овощей, заправить маслом, горчицей и лимонным соком",
    day9DinnerStep3:
      "Кальмар с кукурузой и огурцом слегка смешать со сметаной как дополнительный перекус",
    day9DinnerNutrition1: "🔥 Калории: ~550 ккал",
    day9DinnerNutrition2: "🥩 Белки: ~38 г",
    day9DinnerNutrition3: "🥑 Жиры: ~32,6 г",
    day9DinnerNutrition4: "🍞 Углеводы: ~50 г",

    day9totalNutrition: "ОБЩИЙ КБЖУ ДНЯ 9",
    day9TotalNutrition1: "🔥 Калории: ~1810 ккал",
    day9TotalNutrition2: "🥩 Белки: ~121 г",
    day9TotalNutrition3: "🥑 Жиры: ~84,6 г",
    day9TotalNutrition4: "🍞 Углеводы: ~190 г",

    title: "Калькулятор калорий",
    mainTitle: "Калькулятор калорий",
    gender: "Пол:",
    male: "Мужчина",
    female: "Женщина",
    age: "Возраст:",
    height: "Рост (см):",
    weight: "Вес (кг):",
    activity: "Уровень активности:",
    act1: "Минимальный (сидячая работа)",
    act2: "Легкая активность (1-3 раза/неделю)",
    act3: "Средняя (3-5 раз/неделю)",
    act4: "Высокая (6-7 раз/неделю)",
    act5: "Очень высокая (спорт каждый день)",
    calculate: "Рассчитать",
    resultTitle: "Ваш результат:",
    maintainLabel: "Поддержание веса:",
    lossLabel: "Для похудения:",
    gainLabel: "Для набора:",
    kcal: "ккал/день"
  },
};

const STORAGE_KEY = "language";
const langSwitch = document.getElementById("lang-switch");

// Отримуємо мову з localStorage або ставимо uk
let currentLang = localStorage.getItem(STORAGE_KEY) || "uk";
applyLanguage(currentLang);

// Встановлюємо стан перемикача
langSwitch.checked = currentLang === "ru";

langSwitch.addEventListener("change", () => {
  currentLang = langSwitch.checked ? "ru" : "uk";
  localStorage.setItem(STORAGE_KEY, currentLang);
  applyLanguage(currentLang);
});

function applyLanguage(lang) {
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key];
  });
}
